# nb_02_vector_spaces

Span, basis, dimension, and linear independence with examples.

## Linear independence test using rank
A set of vectors is independent iff the matrix with those vectors as columns has full column rank.

In [1]:
import numpy as np
A = np.array([[1,2,3],[0,1,4],[0,0,1]], dtype=float)
print('A =\n', A)
print('rank(A)=', np.linalg.matrix_rank(A))

A =
 [[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
rank(A)= 3


## Find a basis for the column space (using QR)

In [2]:
Q,R = np.linalg.qr(A)
print('Q=\n', Q)
print('R=\n', R)
# columns of Q corresponding to independent columns form an orthonormal basis


Q=
 [[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]
R=
 [[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]


### Example: express vector in a given basis
If B = [b1 b2] then coordinates c satisfy B c = v, so c = B^{-1} v (if B square/invertible).

In [3]:
B = np.array([[1,1],[0,1]], dtype=float)
v = np.array([3,2], dtype=float)
coords = np.linalg.inv(B).dot(v)
print('coords in basis B =', coords)
print('reconstructed v =', B.dot(coords))

coords in basis B = [1. 2.]
reconstructed v = [3. 2.]
