# nb_03_projections_and_least_squares

Projection onto a subspace, projection matrix, and least squares (normal equations).

## Projection matrix
For full-column-rank A (m x n), the projection matrix onto col(A) is:

\(P = A(A^T A)^{-1} A^T\)

Check properties: symmetric (P = P^T) and idempotent (P^2 = P).

In [1]:
import numpy as np
A = np.array([[1,0],[1,1],[1,2]], dtype=float)
P = A.dot(np.linalg.inv(A.T.dot(A))).dot(A.T)
print('P=\n', P)
# symmetric?
print('P - P^T norm =', np.linalg.norm(P - P.T))
# idempotent?
print('P^2 - P norm =', np.linalg.norm(P.dot(P) - P))

P=
 [[ 0.83333333  0.33333333 -0.16666667]
 [ 0.33333333  0.33333333  0.33333333]
 [-0.16666667  0.33333333  0.83333333]]
P - P^T norm = 0.0
P^2 - P norm = 2.6910028968576024e-16


## Least squares solution
Given A x ≈ b with more equations than unknowns, the normal equations give x̂ = (A^T A)^{-1} A^T b.

In [2]:
b = np.array([1.0, 2.0, 2.5])
x_hat = np.linalg.inv(A.T.dot(A)).dot(A.T).dot(b)
print('x_hat =', x_hat)
print('residual norm =', np.linalg.norm(A.dot(x_hat)-b))

x_hat = [1.08333333 0.75      ]
residual norm = 0.2041241452319315


### Numerical caution
Computing \((A^T A)^{-1}\) can be unstable if A has collinear columns. Use `np.linalg.lstsq` or QR for stability.

In [3]:
# using numpy lstsq
x_hat2, res, rank, s = np.linalg.lstsq(A,b, rcond=None)
print('x_hat2 =', x_hat2)
print('residuals =', res)

x_hat2 = [1.08333333 0.75      ]
residuals = [0.04166667]
